export const TEXTOS = {
  es: {
    "idioma.otro": "PT",
    "comun.volver": "Volver",
    "comun.ocultar": "Ocultar saldos",
    "comun.mostrar": "Mostrar saldos",
    "comun.cargando": "Cargando…",
    "comun.email": "Email",
    "comun.contrasena": "Contraseña",
    "comun.cuenta": "Cuenta",
    "comun.moneda": "Moneda",
    "comun.monto": "Monto",
    "comun.elige": "Elige una cuenta",
    "comun.sinCuentas": "Primero crea una cuenta.",
    "comun.principal": "Principal",
    "comun.hacerPrincipal": "Usar como principal",
    "comun.verMas": "Ver más",
    "comun.verMenos": "Ver menos",
    "comun.enviando": "Enviando…",
    "comun.saldoResultante": "Saldo resultante",
    "menu.abrir": "Abrir menú",
    "menu.cerrar": "Cerrar menú",
    "menu.opciones": "Opciones",
    "menu.dinero": "Dinero",
    "menu.mas": "Más",
    "menu.crear": "Crear cuenta",
    "menu.crearTexto": "Una cuenta en PEN, USD o BRL",
    "menu.depositar": "Depositar",
    "menu.depositarTexto": "Sumar dinero",
    "menu.retirar": "Retirar",
    "menu.retirarTexto": "Solo el dueño de la cuenta",
    "menu.transferir": "Transferir",
    "menu.transferirTexto": "Propia, de otra persona o de otro banco",
    "menu.extracto": "Extracto",
    "menu.extractoTexto": "Movimientos de una cuenta",
    "menu.saldo": "Consultar saldo",
    "menu.saldoTexto": "Detalle de una cuenta",
    "menu.auditoria": "Auditoría",
    "menu.auditoriaTexto": "Cuadre de saldos del nodo",
    "menu.estado": "Estado del nodo",
    "menu.estadoTexto": "Quién atendió esta sesión",
    "menu.salir": "Cerrar sesión",
    "menu.salirTexto": "Salir de este dispositivo",
    "inicio.titulo": "Inicio",
    "inicio.saldo": "Saldo disponible",
    "inicio.cuentas": "Tus cuentas",
    "inicio.cargando": "Cargando cuentas…",
    "inicio.vacio": "Todavía no hay cuentas a tu nombre.",
    "inicio.crear": "Crear la primera",
    "inicio.error": "No pude actualizar los saldos.",
    "atajo.depositar": "Depositar",
    "atajo.transferir": "Transferir",
    "atajo.retirar": "Retirar",
    "atajo.extracto": "Extracto",
    "login.titulo": "Iniciar sesión",
    "login.banco": "Banco distribuido",
    "login.tagline": "Cuentas, depósitos y transferencias",
    "login.entrar": "Entrar",
    "login.entrando": "Entrando…",
    "login.crear": "Crear usuario",
    "login.recuperar": "Recuperar contraseña",
    "login.error": "Email o contraseña incorrectos",
    "registro.titulo": "Crear usuario",
    "registro.nombre": "Nombre",
    "registro.nueva": "Contraseña",
    "registro.acepto": "Acepto los",
    "registro.terminos": "términos y condiciones",
    "registro.boton": "Registrarme",
    "registro.creando": "Creando…",
    "registro.corta": "La contraseña necesita al menos 8 caracteres",
    "registro.aviso": "Usuario creado. Ya puedes entrar.",
    "registro.dialogo": "Términos y condiciones",
    "recuperar.titulo": "Recuperar contraseña",
    "recuperar.aviso": "No hay correo de confirmación. Si el email existe, esta pantalla le pone la contraseña nueva.",
    "recuperar.nueva": "Contraseña nueva",
    "recuperar.repetir": "Repetir contraseña",
    "recuperar.noCoincide": "Las contraseñas no coinciden",
    "recuperar.guardando": "Guardando…",
    "recuperar.boton": "Actualizar contraseña",
    "terminos.titulo": "Términos",
    "terminos.h2": "Términos y condiciones",
    "terminos.p1": "Este banco es un proyecto de curso. No es una entidad financiera, no custodia dinero real y no tiene rol de administrador.",
    "terminos.p2": "Al registrarte guardamos tu nombre, tu email y un hash de la contraseña en el nodo que atiende el alta. La sesión dura 8 horas. Quien tenga el email puede definir una contraseña nueva desde «Recuperar contraseña», porque no hay servidor de correo que confirme la identidad.",
    "terminos.p3": "Las operaciones de saldo, retiro, extracto y transferencia exigen esa sesión y que la cuenta sea tuya. Crear cuenta y depositar, en la API actual, no piden sesión.",
    "terminos.cerrar": "Cerrar",
    "crear.titulo": "Crear cuenta",
    "crear.inicial": "Saldo inicial",
    "crear.boton": "Crear cuenta",
    "crear.creando": "Creando…",
    "crear.sesion": "La sesión no trae un usuario. Vuelve a entrar.",
    "crear.lista": "Ya aparece en Inicio.",
    "deposito.titulo": "Depositar",
    "retiro.titulo": "Retirar",
    "saldo.titulo": "Consultar saldo",
    "saldo.boton": "Consultar",
    "saldo.consultando": "Consultando…",
    "extracto.titulo": "Extracto",
    "extracto.boton": "Ver extracto",
    "extracto.buscando": "Buscando…",
    "extracto.vacio": "Esta cuenta no tiene movimientos.",
    "transfer.titulo": "Transferir",
    "transfer.tipo": "¿A dónde va el dinero?",
    "transfer.propia": "Cuenta propia",
    "transfer.propiaTexto": "Entre las cuentas de tu nombre. Si la moneda cambia, es una conversión.",
    "transfer.otro": "Otra persona",
    "transfer.otroTexto": "Escribes el número de cuenta. La moneda tiene que ser la misma.",
    "transfer.banco": "Otro banco",
    "transfer.bancoTexto": "Una cuenta fuera de este banco.",
    "transfer.origen": "Cuenta de origen",
    "transfer.destino": "Cuenta de destino",
    "transfer.numero": "Número de cuenta",
    "transfer.bancoNombre": "Banco",
    "transfer.boton": "Transferir",
    "transfer.conversion": "Convertir",
    "transfer.mismaMoneda": "La conversión solo se hace entre tus cuentas. Para otra persona, las dos cuentas tienen que ser de la misma moneda.",
    "transfer.bancoPendiente": "La transferencia a otro banco todavía no está disponible en el nodo.",
    "transfer.numeroMal": "Ese número no corresponde a una cuenta.",
    "auditoria.titulo": "Auditoría",
    "auditoria.aviso": "Compara la suma de saldos con el log del nodo que atendió la llamada. No hay rol administrador.",
    "auditoria.boton": "Auditar nodo",
    "auditoria.calculando": "Calculando…",
    "auditoria.saldos": "Suma de saldos",
    "auditoria.log": "Suma del log",
    "auditoria.diff": "Diferencia",
    "auditoria.diverge": "Hay divergencia",
    "auditoria.cuadra": "Cuadra",
    "estado.titulo": "Estado del nodo",
    "estado.aviso": "El balanceador elige un nodo vivo y muestra su estado. No lista el clúster entero.",
    "estado.boton": "Consultar estado",
    "estado.consultando": "Consultando…",
    "estado.nodo": "Nodo",
    "estado.rol": "Rol",
    "estado.epoch": "Epoch",
    "op.CREACION": "Apertura",
    "op.DEPOSITO": "Depósito",
    "op.RETIRO": "Retiro",
    "op.TRANSFERENCIA": "Transferencia",
    "op.CAMBIO": "Conversión",
  },
  pt: {
    "idioma.otro": "ES",
    "comun.volver": "Voltar",
    "comun.ocultar": "Ocultar saldos",
    "comun.mostrar": "Mostrar saldos",
    "comun.cargando": "Carregando…",
    "comun.email": "E-mail",
    "comun.contrasena": "Senha",
    "comun.cuenta": "Conta",
    "comun.moneda": "Moeda",
    "comun.monto": "Valor",
    "comun.elige": "Escolha uma conta",
    "comun.sinCuentas": "Primeiro abra uma conta.",
    "comun.principal": "Principal",
    "comun.hacerPrincipal": "Usar como principal",
    "comun.verMas": "Ver mais",
    "comun.verMenos": "Ver menos",
    "comun.enviando": "Enviando…",
    "comun.saldoResultante": "Saldo resultante",
    "menu.abrir": "Abrir menu",
    "menu.cerrar": "Fechar menu",
    "menu.opciones": "Opções",
    "menu.dinero": "Dinheiro",
    "menu.mas": "Mais",
    "menu.crear": "Abrir conta",
    "menu.crearTexto": "Uma conta em PEN, USD ou BRL",
    "menu.depositar": "Depositar",
    "menu.depositarTexto": "Somar dinheiro",
    "menu.retirar": "Sacar",
    "menu.retirarTexto": "Só o dono da conta",
    "menu.transferir": "Transferir",
    "menu.transferirTexto": "Própria, de outra pessoa ou de outro banco",
    "menu.extracto": "Extrato",
    "menu.extractoTexto": "Movimentos de uma conta",
    "menu.saldo": "Consultar saldo",
    "menu.saldoTexto": "Detalhe de uma conta",
    "menu.auditoria": "Auditoria",
    "menu.auditoriaTexto": "Conferência dos saldos do nó",
    "menu.estado": "Estado do nó",
    "menu.estadoTexto": "Quem atendeu esta sessão",
    "menu.salir": "Sair",
    "menu.salirTexto": "Sair deste aparelho",
    "inicio.titulo": "Início",
    "inicio.saldo": "Saldo disponível",
    "inicio.cuentas": "Suas contas",
    "inicio.cargando": "Carregando contas…",
    "inicio.vacio": "Ainda não há contas no seu nome.",
    "inicio.crear": "Abrir a primeira",
    "inicio.error": "Não consegui atualizar os saldos.",
    "atajo.depositar": "Depositar",
    "atajo.transferir": "Transferir",
    "atajo.retirar": "Sacar",
    "atajo.extracto": "Extrato",
    "login.titulo": "Entrar",
    "login.banco": "Banco distribuído",
    "login.tagline": "Contas, depósitos e transferências",
    "login.entrar": "Entrar",
    "login.entrando": "Entrando…",
    "login.crear": "Criar usuário",
    "login.recuperar": "Recuperar senha",
    "login.error": "E-mail ou senha incorretos",
    "registro.titulo": "Criar usuário",
    "registro.nombre": "Nome",
    "registro.nueva": "Senha",
    "registro.acepto": "Aceito os",
    "registro.terminos": "termos e condições",
    "registro.boton": "Cadastrar",
    "registro.creando": "Criando…",
    "registro.corta": "A senha precisa de pelo menos 8 caracteres",
    "registro.aviso": "Usuário criado. Já pode entrar.",
    "registro.dialogo": "Termos e condições",
    "recuperar.titulo": "Recuperar senha",
    "recuperar.aviso": "Não há e-mail de confirmação. Se o e-mail existe, esta tela define a senha nova.",
    "recuperar.nueva": "Senha nova",
    "recuperar.repetir": "Repetir senha",
    "recuperar.noCoincide": "As senhas não coincidem",
    "recuperar.guardando": "Salvando…",
    "recuperar.boton": "Atualizar senha",
    "terminos.titulo": "Termos",
    "terminos.h2": "Termos e condições",
    "terminos.p1": "Este banco é um projeto de curso. Não é uma instituição financeira, não custodia dinheiro real e não tem papel de administrador.",
    "terminos.p2": "No cadastro guardamos seu nome, seu e-mail e um hash da senha no nó que atende a abertura. A sessão dura 8 horas. Quem tiver o e-mail pode definir uma senha nova em «Recuperar senha», porque não há servidor de e-mail que confirme a identidade.",
    "terminos.p3": "Saldo, saque, extrato e transferência exigem essa sessão e que a conta seja sua. Abrir conta e depositar, na API atual, não pedem sessão.",
    "terminos.cerrar": "Fechar",
    "crear.titulo": "Abrir conta",
    "crear.inicial": "Saldo inicial",
    "crear.boton": "Abrir conta",
    "crear.creando": "Abrindo…",
    "crear.sesion": "A sessão não traz um usuário. Entre de novo.",
    "crear.lista": "Já aparece no Início.",
    "deposito.titulo": "Depositar",
    "retiro.titulo": "Sacar",
    "saldo.titulo": "Consultar saldo",
    "saldo.boton": "Consultar",
    "saldo.consultando": "Consultando…",
    "extracto.titulo": "Extrato",
    "extracto.boton": "Ver extrato",
    "extracto.buscando": "Buscando…",
    "extracto.vacio": "Esta conta não tem movimentos.",
    "transfer.titulo": "Transferir",
    "transfer.tipo": "Para onde vai o dinheiro?",
    "transfer.propia": "Conta própria",
    "transfer.propiaTexto": "Entre as contas do seu nome. Se a moeda muda, é uma conversão.",
    "transfer.otro": "Outra pessoa",
    "transfer.otroTexto": "Você digita o número da conta. A moeda tem de ser a mesma.",
    "transfer.banco": "Outro banco",
    "transfer.bancoTexto": "Uma conta fora deste banco.",
    "transfer.origen": "Conta de origem",
    "transfer.destino": "Conta de destino",
    "transfer.numero": "Número da conta",
    "transfer.bancoNombre": "Banco",
    "transfer.boton": "Transferir",
    "transfer.conversion": "Converter",
    "transfer.mismaMoneda": "A conversão só acontece entre as suas contas. Para outra pessoa, as duas contas têm de ser da mesma moeda.",
    "transfer.bancoPendiente": "A transferência para outro banco ainda não está disponível no nó.",
    "transfer.numeroMal": "Esse número não corresponde a uma conta.",
    "auditoria.titulo": "Auditoria",
    "auditoria.aviso": "Compara a soma dos saldos com o log do nó que atendeu a chamada. Não há papel de administrador.",
    "auditoria.boton": "Auditar nó",
    "auditoria.calculando": "Calculando…",
    "auditoria.saldos": "Soma dos saldos",
    "auditoria.log": "Soma do log",
    "auditoria.diff": "Diferença",
    "auditoria.diverge": "Há divergência",
    "auditoria.cuadra": "Confere",
    "estado.titulo": "Estado do nó",
    "estado.aviso": "O balanceador escolhe um nó vivo e mostra o estado dele. Não lista o cluster inteiro.",
    "estado.boton": "Consultar estado",
    "estado.consultando": "Consultando…",
    "estado.nodo": "Nó",
    "estado.rol": "Papel",
    "estado.epoch": "Epoch",
    "op.CREACION": "Abertura",
    "op.DEPOSITO": "Depósito",
    "op.RETIRO": "Saque",
    "op.TRANSFERENCIA": "Transferência",
    "op.CAMBIO": "Conversão",
  },
};
